name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: pnpm/action-setup@v4.0.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install packages
        run: pnpm install

      - name: Typecheck
        run: pnpm typecheck
      - name: Code Formatting
        run: pnpm fmt:check
      - name: Lint
        run: pnpm lint
